### ISSUE TITLE
ERROR: service [/gazebo_2Dmap_plugin/generate_map] responded with an error

### ISSUE THREAD

**Issue by chinjo1296** [marinaKollmitz/gazebo_ros_2Dmap_plugin#12]
Hello,

I am trying to run this package in Ubuntu 20.04 running ROS Noetic and I am getting the following error

ERROR: service [/gazebo_2Dmap_plugin/generate_map] responded with an error: b'vector::_M_range_check: __n (which is 4275662) >= this->size() (which is 2940000)'

**Comment by chinjo1296** [comment]
It was a problem with the map size not being a square.

**Comment by NamTruongTran** [comment]
Hey Chinjo1296,

i tried to create a 2d grid map with this plugin. 

I tried it with simple turtlebot3_world map but it doesn't work.

After i saved the map, i getting this .pgm file: https://ibb.co/wNB2HdN

Did you know how to solve it?
Thank you.

**Comment by NamTruongTran** [comment]
i fixed it. Thank you anyways ;)
