### ISSUE TITLE
Error running the plugin

### ISSUE THREAD

**Issue by aaravrav142** [marinaKollmitz/gazebo_ros_2Dmap_plugin#2]
Hi, 
I am using this package on ubuntu 16 with ROS kinetic. 
Included the plugin as described right over the `</world>` tag and ran the world file in gazebo as 
`$ gazebo myworld.world 
`
I am getting the following errors: 
```
[FATAL] [1571652019.569040996]: You must call ros::init() before creating the first NodeHandle
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []
[ERROR] [1571652019.611353705]: [registerPublisher] Failed to contact master at [:0].  Retrying...
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []

```
roscore is already running on another terminal. Not sure why the error is so. Can you help me. 

Thanks

**Comment by marinaKollmitz** [comment]
Hi, can you try running gazebo over roslaunch, so do:
roslaunch gazebo_ros empty_world.launch world_file:=<<path_to_worldfile.world>>
