### ISSUE TITLE
Gazebo9 + Gazebo7 support

### ISSUE THREAD

**Issue by ojasjoshi** [marinaKollmitz/gazebo_ros_2Dmap_plugin#9]
I see that currently a separate branch exists for (melodic + gazebo9) support while the mainline supports (kinetic + gazebo7). Is there a plan to support gazebo7 and gazebo9 within the same branch?

For reference, I have made the changes in a [personal fork](https://github.com/ojasjoshi/gazebo_ros_2Dmap_plugin/tree/gazebo7_plus_9). It would be great if these changes could be merged upstream in the mainline or as a separate branch.

**Comment by marinaKollmitz** [comment]
Hi, yes that is a good idea. I am planning to do a cleanup of the package very soon and will try to include the support for gazebo7 and gazebo9 there based on your fork. It would be great if you could help with the testing. Thank you!

**Comment by ojasjoshi** [comment]
Thanks for the positive response. Do you prefer me creating a PR into the mainline based on my fork?

**Comment by ojasjoshi** [comment]
hi @marinaKollmitz, created a PR #10. Can you take a look at the earliest convenience?

**Comment by ojasjoshi** [comment]
hi @marinaKollmitz, pinging for follow-up.

**Comment by marinaKollmitz** [comment]
I am receiving your messages and I will get to it as soon as I can. In the meantime, everyone who wants to can look at the PR and use your fork. Please be patient.

**Comment by marinaKollmitz** [comment]
#10 solves this, thank you @ojasjoshi

**Comment by ojasjoshi** [comment]
Happy to contribute and thanks for taking a look this promptly!
